"""create llm usage events

Revision ID: 7700561e642a
Revises: e3533e1b65a0
Create Date: 2026-10-03 07:04:52.261806

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7700561e642a'
down_revision: Union[str, Sequence[str], None] = 'e3533e1b65a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('llm_usage_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.String(length=36), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('model', sa.String(length=120), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('total_tokens', sa.Integer(), nullable=False),
    sa.Column('tool_calls_requested', sa.Integer(), nullable=False),
    sa.Column('estimated_cost_usd', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_llm_usage_events_conversation_id'), 'llm_usage_events', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_llm_usage_events_model'), 'llm_usage_events', ['model'], unique=False)
    op.create_index(op.f('ix_llm_usage_events_provider'), 'llm_usage_events', ['provider'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_llm_usage_events_provider'), table_name='llm_usage_events')
    op.drop_index(op.f('ix_llm_usage_events_model'), table_name='llm_usage_events')
    op.drop_index(op.f('ix_llm_usage_events_conversation_id'), table_name='llm_usage_events')
    op.drop_table('llm_usage_events')
    # ### end Alembic commands ###
