"""add player identifiers ratings and rbi

Revision ID: e3533e1b65a0
Revises: 42f518aa325d
Create Date: 2026-10-02 10:56:48.442490

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3533e1b65a0'
down_revision: Union[str, Sequence[str], None] = '42f518aa325d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player_season_stats', sa.Column('rbi', sa.Integer(), nullable=False))
    op.add_column('players', sa.Column('mlb_id', sa.Integer(), nullable=False))
    op.add_column('players', sa.Column('contact', sa.Integer(), nullable=True))
    op.add_column('players', sa.Column('power', sa.Integer(), nullable=True))
    op.add_column('players', sa.Column('vision', sa.Integer(), nullable=True))
    op.add_column('players', sa.Column('overall', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_players_mlb_id'), 'players', ['mlb_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_players_mlb_id'), table_name='players')
    op.drop_column('players', 'overall')
    op.drop_column('players', 'vision')
    op.drop_column('players', 'power')
    op.drop_column('players', 'contact')
    op.drop_column('players', 'mlb_id')
    op.drop_column('player_season_stats', 'rbi')
    # ### end Alembic commands ###
